// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIpFEEOy9QVI7XvCtxXs9af17T2NlLesU',
    appId: '1:610716927847:web:ca8075df945f9cb18091c2',
    messagingSenderId: '610716927847',
    projectId: 'employee-db-2327240063',
    authDomain: 'employee-db-2327240063.firebaseapp.com',
    databaseURL: 'https://employee-db-2327240063-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-2327240063.firebasestorage.app',
    measurementId: 'G-EJPGCRQWKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPHVF2yxCNxGLk0FAKZlrKwAjolyzZikQ',
    appId: '1:610716927847:android:e3dc8821c7bb307b8091c2',
    messagingSenderId: '610716927847',
    projectId: 'employee-db-2327240063',
    databaseURL: 'https://employee-db-2327240063-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-2327240063.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5PoFIPCFFUdAwDtce7kI-Ki-miY1qkCU',
    appId: '1:610716927847:ios:f12a4c774069e37c8091c2',
    messagingSenderId: '610716927847',
    projectId: 'employee-db-2327240063',
    databaseURL: 'https://employee-db-2327240063-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-2327240063.firebasestorage.app',
    iosBundleId: 'com.example.employeeMalfatihabdurrohim2327240063',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5PoFIPCFFUdAwDtce7kI-Ki-miY1qkCU',
    appId: '1:610716927847:ios:f12a4c774069e37c8091c2',
    messagingSenderId: '610716927847',
    projectId: 'employee-db-2327240063',
    databaseURL: 'https://employee-db-2327240063-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-2327240063.firebasestorage.app',
    iosBundleId: 'com.example.employeeMalfatihabdurrohim2327240063',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIpFEEOy9QVI7XvCtxXs9af17T2NlLesU',
    appId: '1:610716927847:web:40c257985ddc9cb88091c2',
    messagingSenderId: '610716927847',
    projectId: 'employee-db-2327240063',
    authDomain: 'employee-db-2327240063.firebaseapp.com',
    databaseURL: 'https://employee-db-2327240063-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-2327240063.firebasestorage.app',
    measurementId: 'G-HTXWRN99N7',
  );
}
